# Generated by Django 6.0.2 on 2026-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='task',
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=100),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard'), (5, 'Extreme')]),
        ),
    ]
