# Generated by Django 6.0.2 on 2026-03-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_studysession_task_studysession_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='subject',
        ),
        migrations.AddField(
            model_name='studysession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
